<?php
/**
 * Bitpolar Technologies
 *
 ********************************************************************
 *
 * @category   Bitpolar
 * @package    Bitpolar_CategoryImgWidget
 * @author     Stefan Euchenhofer (info@bitpolar.de)
 * @copyright  Copyright (c) 2019 Bitpolar Technologies (https://www.bitpolar.de)
 */

$categories         = $this->getCategoryCollection();
$canShowCatImg      = $this->canShowCatImage();
$canShowThumbnail   = $this->canShowThumbnail();
$canShowName        = $this->canShowName();
$imgClass           = '';
$imgHeight          = $this->getImageHeight();
$imgWidth           = $this->getImageWidth();

$image = $this->helper('Bitpolar\CategoryImgWidget\Helper\Image');

// Placeholder image
$imageHelper        = $this->helper(\Magento\Catalog\Helper\Image::class);
$imgUrl             = $imageHelper->getDefaultPlaceholderUrl('image');
?>

<div class="block-content catalog-category">
    <ul class="category-list <?php if ($canShowCatImg || $canShowThumbnail): ?>with-images<?php endif;?>">
    <?php foreach ($categories as $category): ?>
        <li class="single-category">

            <?php if ($canShowCatImg || $canShowThumbnail): ?>
                <?php // Set Image URL
                    if ($category->getImageUrl() && $canShowCatImg) {
                        // $imgUrl = $category->getImageUrl();
                        $imgUrl = $image->resize('/'.$category->getImageUrl(), $imgWidth*2, $imgHeight*2);
                        $imgClass = 'category-image';
                    } elseif ($category->getThumbnail() && $canShowThumbnail) {
                        // $imgUrl = $category->getImageUrl('thumbnail');
                        $imgUrl = $image->resize('/'.$category->getThumbnail(), $imgWidth*2, $imgHeight*2);
                        $imgClass = 'thumbnail-image';
                    }
                ?>
                <a href="<?php echo $block->escapeUrl($category->getUrl()) ?>" class="<?php echo $imgClass ?>">
                    <img src="<?php echo $block->escapeUrl($imgUrl) ?>" alt="<?php echo $block->escapeHtml($category->getName()) ?>" width="<?= $imgWidth ?>" height="<?= $imgHeight ?>"/>
                </a>
            <?php endif;?>

            <?php if ($canShowName): ?>
                <a class="category-name" href="<?php echo $block->escapeUrl($category->getUrl()) ?>">
                    <?php echo $block->escapeHtml($category->getName()) ?>
                </a>
            <?php endif;?>

        </li>
    <?php endforeach; ?>
    </ul>
</div>
